### ISSUE TITLE
Use Travis CI to build .NET library

### ISSUE THREAD

**Issue by mcintyre321** [gocardless/gocardless-legacy-dotnet#17]
Currently, the Hat-Tip private build server is used to compile and run builds of the .Net client, while other gocardless libraries are built on Travis.

It seems that it is now possible to build .NET projects on Travis (see http://danlimerick.wordpress.com/2013/02/03/build-your-open-source-net-project-on-travis-ci/), so it might be worthwhile someone following that guide and getting it building on there.

**Comment by barisbalic** [comment]
Thanks for the suggestion @mcintyre321 but for now I don't think it would be suitable, for the following reasons:
1. There's no direct support, so if something changed and stopped this from being possible we'd be lumbered with moving to another service again.
2. This method leverages Mono, which is a fantastic project, but has caused a couple of issues when building/testing locally.  I've managed to get it building and mostly passing, but the changes are not things that I would want to commit.
