### ISSUE TITLE
'state' parameter missing from GoCardless.Partner.NewMerchantUrl

### ISSUE THREAD

**Issue by timrogers** [gocardless/gocardless-legacy-dotnet#2]
The GoCardless API supports a 'state' parameter for passing information through the OAuth flow. This is mentioned in the .NET library documentation, but the functionality is missing from the NewMerchantUrl method.

**Expected behaviour**: It should be possible to pass a "state" string into the method, receiving this back after the OAuth flow.

https://gocardless.com/docs/dotnet/partner_client_guide#connecting-a-merchant-account

**Comment by timiles** [comment]
You're right. I have added this parameter in the latest commit (https://github.com/gocardless/gocardless-dotnet/commit/b5714da461319fbef79752ae9b9c3a5582c861bd), and updated the sample site to test it.

I can deploy this fix onto NuGet this evening.

**Comment by timiles** [comment]
The latest version (1.0.3) is now up on NuGet - please grab this to get the latest revision.

**Comment by timrogers** [comment]
Cheers!
