### ISSUE TITLE
Add support for charge_customer_at field

### ISSUE THREAD

**Issue by karls** [gocardless/gocardless-legacy-dotnet#20]
When creating a Bill under a PreAuth through the API, `charge_customer_at` field can be passed in. This causes the funds for the Bill to leave the customer's account on the date specified by `charge_customer_at` field.

**Comment by w3developments** [comment]
This has been added to master. You can now optionally pass the charge_customer_at value into the PostBill method.
public BillResponse PostBill(decimal amount, string preAuthorizationId, string name = null, string description = null, DateTime? chargeCustomerAt=null)

And you will receive the value back in the ChargeCustomerAt property of the BillResponse

**Comment by barisbalic** [comment]
@w3developments are we good to close this issue then?

**Comment by w3developments** [comment]
@barisbalic The pull request I submitted was merged into master so, yep, I believe it can be closed.

Thanks

**Comment by barisbalic** [comment]
Thanks for your good work!
