### ISSUE TITLE
Add ChargeCustomerAt property to BillResponse

### ISSUE THREAD

**Issue by oobayly** [gocardless/gocardless-legacy-dotnet#25]
It would be handy to have the ChargeCustomerAt property added to the BillResponse class.

I've gone ahead and added it to my local version:

``` C#
public DateTime? ChargeCustomerAt { get; set; } // "2011-11-04T21: 41: 25Z",
\\\
```

**Comment by timrogers** [comment]
@w3developments has already done this in https://github.com/gocardless/gocardless-dotnet/pull/23, but it's yet to be merged.

**Comment by oobayly** [comment]
Ah, missed the bit about the property in that one. Thanks

**Comment by w3developments** [comment]
This has now been merged to master.

**Comment by barisbalic** [comment]
Closing as this has apparently been merged into master, can reopen if somethings missing.
