### ISSUE TITLE
Optional parameters missing on PreAuthorizationRequest

### ISSUE THREAD

**Issue by timrogers** [gocardless/gocardless-legacy-dotnet#3]
The GoCardless API supports a number of optional parameters on pre-authorisations in the Connect flow, including expires_at and interval_count - these appear not to be supported in the library.

https://gocardless.com/docs/connect_guide#payment-types

Many thanks!

_Tim at GoCardless_

**Comment by timiles** [comment]
I believe the PreAuthorizationRequest does in fact contain all the optional params that are currently available - see here: https://github.com/gocardless/gocardless-dotnet/blob/master/GoCardlessSdk/Connect/PreAuthorizationRequest.cs

Is this what you're asking about?
