### ISSUE TITLE
URL parameter encoding is not Culture Invariant

### ISSUE THREAD

**Issue by banderous** [gocardless/gocardless-legacy-dotnet#6]
A Ukrainian user encountered a problem with the URLs generated by the .NET library. Specifically, decimal numbers were formatted with a comma "," decimal separator. 

All our parameter ToString() formatting calls should use the overload that takes a CultureInfo parameter, and supply CultureInfo.InvariantCulture.

**Comment by timiles** [comment]
You're right. Have created a unit test to catch this case, and applied the fix. Latest version (1.1.4) is now available on NuGet. Good spot & apologies!
