### ISSUE TITLE
Pass 'amount' as a string when creating a bill in the API

### ISSUE THREAD

**Issue by timrogers** [gocardless/gocardless-legacy-dotnet#9]
The 'post_bill' method in https://github.com/gocardless/gocardless-dotnet/blob/master/GoCardlessSdk/Api/ApiClient.cs, when serializing to JSON, is converting the 'amount' field from a decimal to a number in JSON. It should be passed to us as a string.

You'd usually expect this to not be the case, but converting the number is causing rounding errors and thus unexpected consequences when we try to convert it back on GoCardless.

**Expected behaviour** - The 'bill' -> 'amount' attribute should be a string

**Comment by timrogers** [comment]
Tim to get in touch with Glenn at Quick File once this issue is resolved.

**Comment by mcintyre321** [comment]
Hi Tim, I've sent you an email re: this. Please get in touch if you don't receive it.

**Comment by banderous** [comment]
Presumably this is because JSON numbers are interpreted as floating point.

**Comment by mcintyre321** [comment]
Hi I've just checked in a fix for this - see https://github.com/gocardless/gocardless-dotnet/commit/47955210bfa2ebee7b7c3b1c0a7a1c502004687f
